In [7]:
import pandas as pd
import numpy as np
from sklearn.utils import resample
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from IPython.display import display, HTML

In [72]:
# 데이터 로드
df = pd.read_csv("predictions.csv")

In [73]:
df.head()

,user_id,성별,연령대,나이,키,현재 체중,목표 체중,BMI,허리둘레,수축기혈압,...,트리글리세라이드,식전혈당(공복혈당),활동 수준,흡연상태,음주여부,운동 가능성,운동 점수,식단 개선 필요성,식단 점수,예측 날짜
0,게스트,남성,5.0,25.0,170.0,70.0,65.0,24.22,80.0,120.0,...,150.0,90.0,중간활동,비흡연,비음주,🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",2025-02-20 02:42:09
1,generated_id_1,남성,5.0,25.0,170.0,70.0,65.0,24.22,80.0,120.0,...,150.0,90.0,저활동,비흡연,비음주,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,2025-02-17 18:59:36
2,generated_id_2,남성,5.0,25.0,170.0,70.0,65.0,24.22,80.0,120.0,...,150.0,90.0,저활동,비흡연,비음주,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,2025-02-17 18:59:36
3,generated_id_3,남성,5.0,25.0,170.0,70.0,65.0,24.22,80.0,120.0,...,150.0,90.0,저활동,비흡연,비음주,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,2025-02-17 18:59:36
4,generated_id_4,남성,5.0,25.0,170.0,70.0,65.0,24.22,80.0,120.0,...,150.0,90.0,저활동,비흡연,비음주,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,2025-02-17 18:59:36

In [74]:
def merge_columns(df, columns, target_column):
    """지정된 컬럼들의 데이터를 병합하여 target_column으로 만듭니다."""
    df[target_column] = df[columns].apply(
        lambda row: next((val for val in row if pd.notna(val)), np.nan), axis=1
    )
    return df

In [75]:
# 동일한 의미의 중복 컬럼 리스트
duplicate_columns = {
    "user_id": ["user_id"],
    "성별": ["성별", "gender"],
    "연령대": ["연령대", "age"],
    "BMI": ["BMI"],
    "현재 체중": ["현재 체중", "weight"],
    "목표 체중": ["목표 체중", "goal_weight"],
    "운동 가능성": ["운동 가능성"],
    "운동 점수": ["운동 점수", "운동 확률"],
    "식단 개선 필요성": ["식단 개선 필요성"],
    "식단 점수": ["식단 확률", "식단 점수"],
    "예측 날짜": ["예측 날짜"],
    "허리둘레": ["허리둘레 (cm)", "허리둘레 (cm).1", "waist", "허리둘레"],
    "키": ["키 (cm)", "height"],
    "수축기혈압(최고 혈압)": ["수축기혈압(최고 혈압)", "systolic_bp"],
    "이완기혈압(최저 혈압)": ["이완기혈압(최저 혈압)", "diastolic_bp"],
    "콜레스테롤": ["콜레스테롤 지수", "cholesterol", "총콜레스테롤"],
    "활동 수준": ["활동 수준", "activity_level", "activity_level_code"],
    "HDL콜레스테롤": ["HDL콜레스테롤"],
    "LDL콜레스테롤": ["LDL콜레스테롤"],
    "트리글리세라이드": ["트리글리세라이드"],
    "흡연상태": ["흡연상태"],
    "음주여부": ["음주여부"],
    "혈압 차이": ["혈압 차이"],
    "고혈당 위험": ["고혈당 위험"],
    "간 지표": ["간 지표"],
    "비만 위험 지수": ["비만 위험 지수"],
    "식전혈당(공복혈당)": ["식전혈당(공복혈당)"]
}

In [76]:
# 각 그룹의 컬럼들을 병합하고 대표 컬럼으로 이름을 변경합니다
for rep_col, dup_cols in duplicate_columns.items():
    if len(dup_cols) > 1:
        existing_cols = [col for col in dup_cols if col in df.columns]
        if existing_cols:
            df = merge_columns(df, existing_cols, rep_col)
            # 원래 컬럼들 삭제 (대표 컬럼 제외)
            df.drop(columns=[col for col in existing_cols if col != rep_col], inplace=True)
    elif dup_cols[0] in df.columns and dup_cols[0] != rep_col:
        # 컬럼 이름만 변경
        df.rename(columns={dup_cols[0]: rep_col}, inplace=True)

In [77]:
# 결과 확인
print(df.columns)

Index(['user_id', '성별', '연령대', '나이', '키', '현재 체중', '목표 체중', 'BMI', '허리둘레',
       '수축기혈압', '이완기혈압', '혈압 차이', '콜레스테롤', 'HDL콜레스테롤', 'LDL콜레스테롤', '트리글리세라이드',
       '식전혈당(공복혈당)', '활동 수준', '흡연상태', '음주여부', '운동 가능성', '운동 점수', '식단 개선 필요성',
       '식단 점수', '예측 날짜'],
      dtype='object')

In [78]:
df.columns.nunique()

25

In [79]:
column_categories = {
    '기본 정보': ['user_id', '성별', '연령대', '나이', '키', '현재 체중', '목표 체중', 'BMI', '허리둘레'],
    '건강 지표': ['수축기혈압', '이완기혈압', '혈압 차이', '콜레스테롤', 'HDL콜레스테롤', 'LDL콜레스테롤', '트리글리세라이드', '식전혈당(공복혈당)'],
    '생활 습관': ['활동 수준', '흡연상태', '음주여부'],
    '건강 위험': ['고혈당 위험', '간 지표', '비만 위험 지수'],
    '예측 및 점수': ['운동 가능성', '운동 점수', '식단 개선 필요성', '식단 점수', '예측 날짜']
}

In [91]:
new_columns = ['user_id', '성별', '연령대', '나이', '키', '현재 체중', '목표 체중', 'BMI', '허리둘레',
               "수축기혈압(최고 혈압)", "이완기혈압(최저 혈압)", '혈압 차이', '콜레스테롤', 'HDL콜레스테롤', 'LDL콜레스테롤', 
               '트리글리세라이드', '식전혈당(공복혈당)', '활동 수준', '흡연상태', '음주여부','고혈당 위험', '간 지표', '비만 위험 지수'
               '운동 가능성', '운동 점수', '식단 개선 필요성', '식단 점수', '예측 날짜']

In [92]:
df = df.reindex(columns=new_columns)

In [93]:
df.head()

,user_id,성별,연령대,나이,키,현재 체중,목표 체중,BMI,허리둘레,수축기혈압(최고 혈압),...,활동 수준,흡연상태,음주여부,고혈당 위험,간 지표,비만 위험 지수운동 가능성,운동 점수,식단 개선 필요성,식단 점수,예측 날짜
0,user_0,남성,50대,46,165.3,64.2,98.9,21.2,103.5,NaN,...,보통,과거 흡연,자주,NaN,NaN,NaN,33,60,83,2025-05-26 19:37:03.888373
1,user_1,여성,40대,17,157.1,117.5,82.0,29.4,93.2,NaN,...,보통,현재 흡연,자주,NaN,NaN,NaN,2,46,7,2024-08-23 19:37:03.888373
2,user_2,남성,60대 이상,58,181.8,67.4,46.6,23.8,87.5,NaN,...,낮음,현재 흡연,비음주,NaN,NaN,NaN,86,0,78,2025-01-21 19:37:03.888373
3,user_3,여성,20대,32,157.1,110.3,51.1,26.8,61.5,NaN,...,보통,현재 흡연,자주,NaN,NaN,NaN,73,53,99,2024-02-26 19:37:03.888373
4,user_4,남성,20대,41,188.4,107.7,51.8,16.1,107.7,NaN,...,보통,비흡연,자주,NaN,NaN,NaN,83,47,84,2025-11-17 19:37:03.888373

In [94]:
df.columns

Index(['user_id', '성별', '연령대', '나이', '키', '현재 체중', '목표 체중', 'BMI', '허리둘레',
       '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '혈압 차이', '콜레스테롤', 'HDL콜레스테롤',
       'LDL콜레스테롤', '트리글리세라이드', '식전혈당(공복혈당)', '활동 수준', '흡연상태', '음주여부', '고혈당 위험',
       '간 지표', '비만 위험 지수운동 가능성', '운동 점수', '식단 개선 필요성', '식단 점수', '예측 날짜'],
      dtype='object')

In [95]:
df.to_csv("predictions.csv", index=False)

In [96]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

def generate_random_data(num_rows=1000):
    # 현재 날짜 기준으로 1년 전부터 1년 후까지의 날짜 범위 설정
    date_start = datetime.now() - timedelta(days=365)
    date_end = datetime.now() + timedelta(days=365)

    data = {
        'user_id': [f'user_{i}' for i in range(num_rows)],
        '성별': np.random.choice(['남성', '여성'], num_rows),
        '연령대': np.random.choice(['10대', '20대', '30대', '40대', '50대', '60대 이상'], num_rows),
        '나이': np.random.randint(10, 80, num_rows),
        '키': np.random.uniform(150, 190, num_rows).round(1),
        '현재 체중': np.random.uniform(40, 120, num_rows).round(1),
        '목표 체중': np.random.uniform(40, 120, num_rows).round(1),
        'BMI': np.random.uniform(15, 35, num_rows).round(1),
        '허리둘레': np.random.uniform(60, 120, num_rows).round(1),
        '수축기혈압(최고 혈압)': np.random.randint(90, 180, num_rows),
        '이완기혈압(최저 혈압)': np.random.randint(60, 120, num_rows),
        '혈압 차이': np.random.randint(20, 80, num_rows),
        '콜레스테롤': np.random.randint(100, 300, num_rows),
        'HDL콜레스테롤': np.random.randint(30, 100, num_rows),
        'LDL콜레스테롤': np.random.randint(50, 200, num_rows),
        '트리글리세라이드': np.random.randint(50, 500, num_rows),
        '식전혈당(공복혈당)': np.random.randint(70, 200, num_rows),
        '활동 수준': np.random.choice(['낮음', '보통', '높음'], num_rows),
        '흡연상태': np.random.choice(['비흡연', '과거 흡연', '현재 흡연'], num_rows),
        '음주여부': np.random.choice(['비음주', '가끔', '자주'], num_rows),
        '고혈당 위험': np.random.choice(['낮음', '보통', '높음'], num_rows),
        '간 지표': np.random.choice(['정상', '경계', '위험'], num_rows),
        '비만 위험 지수': np.random.uniform(0, 100, num_rows).round(1),
        '운동 가능성': np.random.randint(0, 101, num_rows),
        '운동 점수': np.random.randint(0, 101, num_rows),
        '식단 개선 필요성': np.random.randint(0, 101, num_rows),
        '식단 점수': np.random.randint(0, 101, num_rows),
        '예측 날짜': [date_start + timedelta(days=np.random.randint(0, 730)) for _ in range(num_rows)]
    }

    return pd.DataFrame(data)

# 랜덤 데이터 생성
df = generate_random_data()

# 결과 확인
print(df.head())
print(df.dtypes)

  user_id  성별     연령대  나이      키  현재 체중  목표 체중   BMI   허리둘레  수축기혈압(최고 혈압)  \
0  user_0  남성  60대 이상  70  188.9   45.3   45.7  24.4   87.8           145
1  user_1  남성     50대  65  160.4  112.8   72.4  17.9  116.5           155
2  user_2  남성     50대  37  151.8   44.4   68.3  24.5   83.1           115
3  user_3  여성     40대  47  157.5  109.0  110.1  23.4   85.8           143
4  user_4  남성  60대 이상  10  155.3  105.1   56.1  27.0   66.8            94

   ...   흡연상태  음주여부  고혈당 위험  간 지표  비만 위험 지수  운동 가능성  운동 점수 식단 개선 필요성 식단 점수  \
0  ...  현재 흡연    가끔      높음    경계      23.7      81     96        61    97
1  ...  현재 흡연    자주      보통    위험      52.7      39     20        30    22
2  ...  과거 흡연   비음주      낮음    경계      28.9       9     74        94    15
3  ...    비흡연   비음주      낮음    위험      48.1       5     79        71    23
4  ...    비흡연    가끔      보통    정상      21.8      33     60        85     6

                       예측 날짜
0 2024-03-25 19:42:56.011806
1 2025-05-20 19:42:56.011806
2 2024-04-30 19:42:56.011806
3 2024-09-22 19:42:56.011806
4 2024-10-22 19:42:56.011806

[5 rows x 28 columns]
user_id                 object
성별                      object
연령대                     object
나이                       int64
키                      float64
현재 체중                  float64
목표 체중                  float64
BMI                    float64
허리둘레                   float64
수축기혈압(최고 혈압)             int64
이완기혈압(최저 혈압)             int64
혈압 차이                    int64
콜레스테롤                    int64
HDL콜레스테롤                 int64
LDL콜레스테롤                 int64
트리글리세라이드                 int64
식전혈당(공복혈당)               int64
활동 수준                   object
흡연상태                    object
음주여부                    object
고혈당 위험                  object
간 지표                    object
비만 위험 지수               float64
운동 가능성                   int64
운동 점수                    int64
식단 개선 필요성                int64
식단 점수                    int64
예측 날짜           datetime64[ns]
dtype: object

In [97]:
df.to_csv("predictions.csv", index=False)

In [99]:
df.columns

Index(['user_id', '성별', '연령대', '나이', '키', '현재 체중', '목표 체중', 'BMI', '허리둘레',
       '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '혈압 차이', '콜레스테롤', 'HDL콜레스테롤',
       'LDL콜레스테롤', '트리글리세라이드', '식전혈당(공복혈당)', '활동 수준', '흡연상태', '음주여부', '고혈당 위험',
       '간 지표', '비만 위험 지수', '운동 가능성', '운동 점수', '식단 개선 필요성', '식단 점수', '예측 날짜'],
      dtype='object')

In [100]:
df.head()

,user_id,성별,연령대,나이,키,현재 체중,목표 체중,BMI,허리둘레,수축기혈압(최고 혈압),...,흡연상태,음주여부,고혈당 위험,간 지표,비만 위험 지수,운동 가능성,운동 점수,식단 개선 필요성,식단 점수,예측 날짜
0,user_0,남성,60대 이상,70,188.9,45.3,45.7,24.4,87.8,145,...,현재 흡연,가끔,높음,경계,23.7,81,96,61,97,2024-03-25 19:42:56.011806
1,user_1,남성,50대,65,160.4,112.8,72.4,17.9,116.5,155,...,현재 흡연,자주,보통,위험,52.7,39,20,30,22,2025-05-20 19:42:56.011806
2,user_2,남성,50대,37,151.8,44.4,68.3,24.5,83.1,115,...,과거 흡연,비음주,낮음,경계,28.9,9,74,94,15,2024-04-30 19:42:56.011806
3,user_3,여성,40대,47,157.5,109.0,110.1,23.4,85.8,143,...,비흡연,비음주,낮음,위험,48.1,5,79,71,23,2024-09-22 19:42:56.011806
4,user_4,남성,60대 이상,10,155.3,105.1,56.1,27.0,66.8,94,...,비흡연,가끔,보통,정상,21.8,33,60,85,6,2024-10-22 19:42:56.011806

In [67]:

# 결측치 현황 확인
print("결측치 현황:")
print(df.isnull().sum())
print("\n결측치 비율:")
print(df.isnull().sum() / len(df) * 100)

결측치 현황:
user_id        90
성별             12
연령대            24
나이            329
키             392
현재 체중          81
목표 체중          82
BMI            79
허리둘레          177
수축기혈압         168
이완기혈압         168
혈압 차이         242
콜레스테롤         168
HDL콜레스테롤      204
LDL콜레스테롤      204
트리글리세라이드      204
식전혈당(공복혈당)    296
활동 수준         210
흡연상태          204
음주여부          204
운동 가능성        252
운동 점수           1
식단 개선 필요성     252
식단 점수           1
예측 날짜          88
dtype: int64

결측치 비율:
user_id       21.634615
성별             2.884615
연령대            5.769231
나이            79.086538
키             94.230769
현재 체중         19.471154
목표 체중         19.711538
BMI           18.990385
허리둘레          42.548077
수축기혈압         40.384615
이완기혈압         40.384615
혈압 차이         58.173077
콜레스테롤         40.384615
HDL콜레스테롤      49.038462
LDL콜레스테롤      49.038462
트리글리세라이드      49.038462
식전혈당(공복혈당)    71.153846
활동 수준         50.480769
흡연상태          49.038462
음주여부          49.038462
운동 가능성        60.576923
운동 점수          0.240385
식단 개선 필요성     60.576923
식단 점수          0.240385
예측 날짜         21.153846
dtype: float64

In [69]:

def handle_missing_values(df):
    # 1. 사용자 ID 처리
    if df['user_id'].isnull().sum() > 0:
        print("경고: user_id에 결측치가 있습니다. 이를 고유한 값으로 대체합니다.")
        df['user_id'] = df['user_id'].fillna(pd.Series([f'generated_id_{i}' for i in range(df['user_id'].isnull().sum())]))

    # 2. 범주형 변수: 최빈값으로 대체
    for col in ['성별', '연령대', '활동 수준', '흡연상태', '음주여부']:
        df[col] = df[col].fillna(df[col].mode()[0])

    # 3. 수치형 변수: 중앙값으로 대체
    numeric_cols = ['나이', '키', '현재 체중', '목표 체중', 'BMI', '허리둘레', 
                    '수축기혈압', '이완기혈압', '혈압 차이', '콜레스테롤', 
                    'HDL콜레스테롤', 'LDL콜레스테롤', '트리글리세라이드', '식전혈당(공복혈당)']
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col] = df[col].fillna(df[col].median())

    # 4. 계산 가능한 변수
    df['BMI'] = df['BMI'].fillna(df['현재 체중'] / ((df['키']/100) ** 2))
    df['혈압 차이'] = df['혈압 차이'].fillna(df['수축기혈압'] - df['이완기혈압'])

    # 5. 예측 관련 변수: 40~100 사이의 랜덤값으로 대체
    prediction_cols = ['운동 가능성', '운동 점수', '식단 개선 필요성', '식단 점수']
    for col in prediction_cols:
        null_mask = df[col].isnull()
        df.loc[null_mask, col] = np.random.randint(40, 101, size=null_mask.sum())

    # 6. 날짜 변수
    df['예측 날짜'] = df['예측 날짜'].fillna(df['예측 날짜'].mode()[0])

    return df

# 결측치 처리 적용
df = handle_missing_values(df)

# 처리 후 결측치 현황 재확인
print("\n결측치 처리 후 현황:")
print(df.isnull().sum())

경고: user_id에 결측치가 있습니다. 이를 고유한 값으로 대체합니다.

결측치 처리 후 현황:
user_id       4
성별            0
연령대           0
나이            0
키             0
현재 체중         0
목표 체중         0
BMI           0
허리둘레          0
수축기혈압         0
이완기혈압         0
혈압 차이         0
콜레스테롤         0
HDL콜레스테롤      0
LDL콜레스테롤      0
트리글리세라이드      0
식전혈당(공복혈당)    0
활동 수준         0
흡연상태          0
음주여부          0
운동 가능성        0
운동 점수         0
식단 개선 필요성     0
식단 점수         0
예측 날짜         0
dtype: int64

In [70]:
df.head()

,user_id,성별,연령대,나이,키,현재 체중,목표 체중,BMI,허리둘레,수축기혈압,...,트리글리세라이드,식전혈당(공복혈당),활동 수준,흡연상태,음주여부,운동 가능성,운동 점수,식단 개선 필요성,식단 점수,예측 날짜
0,게스트,남성,5.0,25.0,170.0,70.0,65.0,24.22,80.0,120.0,...,150.0,90.0,중간활동,비흡연,비음주,🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",2025-02-20 02:42:09
1,generated_id_1,남성,5.0,25.0,170.0,70.0,65.0,24.22,80.0,120.0,...,150.0,90.0,저활동,비흡연,비음주,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,2025-02-17 18:59:36
2,generated_id_2,남성,5.0,25.0,170.0,70.0,65.0,24.22,80.0,120.0,...,150.0,90.0,저활동,비흡연,비음주,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,2025-02-17 18:59:36
3,generated_id_3,남성,5.0,25.0,170.0,70.0,65.0,24.22,80.0,120.0,...,150.0,90.0,저활동,비흡연,비음주,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,2025-02-17 18:59:36
4,generated_id_4,남성,5.0,25.0,170.0,70.0,65.0,24.22,80.0,120.0,...,150.0,90.0,저활동,비흡연,비음주,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,2025-02-17 18:59:36

In [71]:
df.to_csv("predictions.csv", index=False)

In [ ]:

# ✅ 동일한 의미의 중복 컬럼 리스트
duplicate_columns = {
"현재 체중": ["현재 체중", "현재 체중 (kg)", "weight"],
"목표 체중": ["목표 체중", "목표 체중 (kg)", "목표체중 (kg)", "goal_weight"],
"연령대": ["연령대", "연령대코드(5세단위)", "age_group"],
"키": ['키 (cm)', "height","키"],
"나이": ["나이", "age"],
"허리둘레": ["허리둘레 (cm)", "waist","허리둘레"],
"수축기혈압(최고 혈압)": ["수축기혈압(최고 혈압)", "systolic_bp"],
"이완기혈압(최저 혈압)": ["이완기혈압(최저 혈압)", "diastolic_bp"],
"콜레스테롤": ["콜레스테롤 지수", "cholesterol","콜레스테롤"],
"활동 수준": [ '활동 수준',"activity_level"],
}

In [ ]:
# ✅ 중복된 컬럼 삭제
df.drop(columns=[
    "prediction_exercise", "prediction_food", "timestamp", "gender"
], inplace=True)

In [49]:
import os

df.to_csv("predictions.csv", index=False)

In [5]:
df.columns

Index(['user_id', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성', '운동 점수',
       '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', '키 (cm)',
       '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준', 'gender', 'age',
       'height', 'weight', 'goal_weight', 'waist', 'systolic_bp',
       'diastolic_bp', 'cholesterol', 'activity_level', 'activity_level_code',
       '허리둘레 (cm).1', 'HDL콜레스테롤', 'LDL콜레스테롤', '트리글리세라이드', '흡연상태', '음주여부',
       '혈압 차이', '총콜레스테롤', '고혈당 위험', '간 지표', '비만 위험 지수', '식전혈당(공복혈당)', '허리둘레',
       '운동 확률', '식단 점수'],
      dtype='object')

In [59]:
# ✅ 동일한 의미의 중복 컬럼 리스트
duplicate_columns = {
    "현재 체중": ["현재 체중", "현재 체중 (kg)", "weight"],
    "목표 체중": ["목표 체중", "목표 체중 (kg)", "목표체중 (kg)", "goal_weight"],
    "연령대": ["연령대", "연령대코드(5세단위)", "age_group"],
    "키": ['키 (cm)', "height","키"],
    "나이": ["나이", "age"],
    "허리둘레": ["허리둘레 (cm)", "waist","허리둘레"],
    "수축기혈압(최고 혈압)": ["수축기혈압(최고 혈압)", "systolic_bp"],
    "이완기혈압(최저 혈압)": ["이완기혈압(최저 혈압)", "diastolic_bp"],
    "콜레스테롤": ["콜레스테롤 지수", "cholesterol","콜레스테롤"],
    "활동 수준": [ '활동 수준',"activity_level"],
}

In [62]:
df.columns

Index(['user_id', '이름', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성',
       '운동 확률', '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', 'ID',
       '키 (cm)', '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준', '활동수준코드',
       '키', '허리둘레', '콜레스테롤', '활동 수준 코드'],
      dtype='object')

In [98]:
# ✅ 컬럼 병합: 첫 번째 값을 유지하거나 평균값 사용
for new_col, old_cols in duplicate_columns.items():
    existing_cols = [col for col in old_cols if col in df.columns]  # 실제 존재하는 컬럼만 선택
    if len(existing_cols) > 1:
        df[new_col] = df[existing_cols].bfill(axis=1).iloc[:, 0]  # 첫 번째 존재하는 값 선택
        df.drop(columns=existing_cols[1:], inplace=True)  # 첫 번째 컬럼 제외하고 나머지는 삭제

In [81]:
df.columns

Index(['user_id', '이름', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성',
       '운동 확률', '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', '키 (cm)',
       '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준'],
      dtype='object')

In [68]:
# ✅ 중복된 컬럼 삭제
df.drop(columns=[
    "ID"
], inplace=True)

In [89]:
# ✅ 동일한 의미의 중복 컬럼 리스트
duplicate_columns = {

    "키": ['키 (cm)', "키"],
    "허리둘레": ["허리둘레 (cm)","허리둘레"]

}

In [90]:
df.columns

Index(['user_id', '이름', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성',
       '운동 확률', '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', '키 (cm)',
       '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준'],
      dtype='object')

In [8]:
# ✅ 컬럼명 변경 딕셔너리
rename_columns = {
    "허리둘레": "허리둘레 (cm)",
    "키": "키 (cm)",
    "운동 확률": "운동 점수",
    "식사 확률": "식사 점수"
}

In [10]:
# 컬럼명 변경
df = df.rename(columns=rename_columns)

In [11]:
df.columns

Index(['user_id', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성', '운동 점수',
       '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', '키 (cm)',
       '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준', 'gender', 'age',
       'height', 'weight', 'goal_weight', 'waist', 'systolic_bp',
       'diastolic_bp', 'cholesterol', 'activity_level', 'activity_level_code',
       '허리둘레 (cm)', 'HDL콜레스테롤', 'LDL콜레스테롤', '트리글리세라이드', '흡연상태', '음주여부',
       '혈압 차이', '총콜레스테롤', '고혈당 위험', '간 지표', '비만 위험 지수', '식전혈당(공복혈당)'],
      dtype='object')

In [6]:
df

,user_id,성별,연령대,BMI,현재 체중,목표 체중,운동 가능성,운동 확률,식단 개선 필요성,식단 확률,...,LDL콜레스테롤,트리글리세라이드,흡연상태,음주여부,혈압 차이,총콜레스테롤,고혈당 위험,간 지표,비만 위험 지수,식전혈당(공복혈당)
0,게스트,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
300,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
301,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
302,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
303,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0

In [12]:
df.to_csv("predictions.csv", index=False)

In [96]:
# ✅ 중복된 컬럼 삭제
df.drop(columns=[
    "이름"
], inplace=True)

In [120]:
# ✅ 중복된 컬럼 병합 (존재하는 값 중 첫 번째 값 유지)
for new_col, old_cols in duplicate_columns.items():
    existing_cols = [col for col in old_cols if col in df.columns]  # 실제 존재하는 컬럼만 선택
    if len(existing_cols) > 1:
        df[new_col] = df[existing_cols].bfill(axis=1).iloc[:, 0]  # 첫 번째 존재하는 값 선택
        df.drop(columns=existing_cols[1:], inplace=True)  # 첫 번째 컬럼 제외하고 나머지는 삭제

In [13]:
df

,user_id,성별,연령대,BMI,현재 체중,목표 체중,운동 가능성,운동 점수,식단 개선 필요성,식단 확률,...,LDL콜레스테롤,트리글리세라이드,흡연상태,음주여부,혈압 차이,총콜레스테롤,고혈당 위험,간 지표,비만 위험 지수,식전혈당(공복혈당)
0,게스트,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
300,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
301,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
302,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
303,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0

In [125]:
# ✅ 후처리 (범위 초과 값 정리)
df["허리둘레 (cm)"] = df["허리둘레 (cm)"].clip(lower=50, upper=150)
df["수축기혈압(최고 혈압)"] = df["수축기혈압(최고 혈압)"].clip(lower=80, upper=200)
df["이완기혈압(최저 혈압)"] = df["이완기혈압(최저 혈압)"].clip(lower=40, upper=130)
df["나이"] = df["나이"].clip(lower=10, upper=100)
df["키 (cm)"] = df["키 (cm)"].clip(lower=100, upper=250)
df["현재 체중"] = df["현재 체중"].clip(lower=30, upper=200)
df["목표 체중"] = df["목표 체중"].clip(lower=30, upper=200)
df["콜레스테롤 지수"] = df["콜레스테롤 지수"].clip(lower=100, upper=300)

In [122]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [123]:
# ✅ 수치형 컬럼 확인 (NaN 값이 있는 컬럼만 선택)
numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()
nan_columns = df[numeric_columns].isna().sum()
nan_columns = nan_columns[nan_columns > 0].index.tolist()  # NaN이 있는 컬럼만 선택

In [127]:
# ✅ 다중대체법(IterativeImputer) 적용 - NaN 값이 있는 컬럼만 변환
imputer = IterativeImputer(max_iter=10, random_state=42)
imputed_values = imputer.fit_transform(df[nan_columns])  # 결과는 Numpy 배열

/opt/anaconda3/envs/hi/lib/python3.10/site-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: [ 0  5  7 15]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(

In [128]:
# ✅ NaN 값이 있는지 확인
if df.isna().sum().sum() == 0:
    print("✅ NaN 값이 모두 채워졌습니다!")
else:
    print("🚨 일부 NaN 값이 남아 있습니다. 다시 확인해주세요!")

🚨 일부 NaN 값이 남아 있습니다. 다시 확인해주세요!

In [131]:
# ✅ 문제 해결: 모든 수치형 컬럼을 float로 변환
numeric_columns = [
    "허리둘레 (cm)", "수축기혈압(최고 혈압)", "이완기혈압(최저 혈압)", "나이",
    "키 (cm)", "현재 체중", "목표 체중", "콜레스테롤 지수"
]
for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")  # 변환 불가한 값은 NaN 처리

In [132]:
# ✅ 다중대체법(IterativeImputer) 적용
imputer = IterativeImputer(max_iter=10, random_state=42)
df[numeric_columns] = imputer.fit_transform(df[numeric_columns])

/opt/anaconda3/envs/hi/lib/python3.10/site-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [134]:
df.columns

Index(['user_id', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성', '운동 확률',
       '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', '키 (cm)',
       '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준'],
      dtype='object')