In [1]:
import pandas as pd
import numpy as np
from sklearn.utils import resample
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
# 데이터 로드
df = pd.read_csv("predictions.csv")

In [3]:
df.head()

,user_id,성별,연령대,BMI,현재 체중,목표 체중,운동 가능성,운동 확률,식단 개선 필요성,식단 확률,...,LDL콜레스테롤,트리글리세라이드,흡연상태,음주여부,혈압 차이,총콜레스테롤,고혈당 위험,간 지표,비만 위험 지수,식전혈당(공복혈당)
0,게스트,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
# ✅ 중복된 컬럼 삭제
df.drop(columns=[
    "prediction_exercise", "prediction_food", "timestamp", "gender"
], inplace=True)

In [49]:
import os

df.to_csv("predictions.csv", index=False)

In [52]:
df.columns

Index(['user_id', '이름', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성',
       '운동 확률', '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', 'ID',
       '키 (cm)', '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준', '활동수준코드',
       '키', '허리둘레', '콜레스테롤', '활동 수준 코드'],
      dtype='object')

In [59]:
# ✅ 동일한 의미의 중복 컬럼 리스트
duplicate_columns = {
    "현재 체중": ["현재 체중", "현재 체중 (kg)", "weight"],
    "목표 체중": ["목표 체중", "목표 체중 (kg)", "목표체중 (kg)", "goal_weight"],
    "연령대": ["연령대", "연령대코드(5세단위)", "age_group"],
    "키": ['키 (cm)', "height","키"],
    "나이": ["나이", "age"],
    "허리둘레": ["허리둘레 (cm)", "waist","허리둘레"],
    "수축기혈압(최고 혈압)": ["수축기혈압(최고 혈압)", "systolic_bp"],
    "이완기혈압(최저 혈압)": ["이완기혈압(최저 혈압)", "diastolic_bp"],
    "콜레스테롤": ["콜레스테롤 지수", "cholesterol","콜레스테롤"],
    "활동 수준": [ '활동 수준',"activity_level"],
}

In [62]:
df.columns

Index(['user_id', '이름', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성',
       '운동 확률', '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', 'ID',
       '키 (cm)', '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준', '활동수준코드',
       '키', '허리둘레', '콜레스테롤', '활동 수준 코드'],
      dtype='object')

In [98]:
# ✅ 컬럼 병합: 첫 번째 값을 유지하거나 평균값 사용
for new_col, old_cols in duplicate_columns.items():
    existing_cols = [col for col in old_cols if col in df.columns]  # 실제 존재하는 컬럼만 선택
    if len(existing_cols) > 1:
        df[new_col] = df[existing_cols].bfill(axis=1).iloc[:, 0]  # 첫 번째 존재하는 값 선택
        df.drop(columns=existing_cols[1:], inplace=True)  # 첫 번째 컬럼 제외하고 나머지는 삭제

In [81]:
df.columns

Index(['user_id', '이름', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성',
       '운동 확률', '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', '키 (cm)',
       '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준'],
      dtype='object')

In [68]:
# ✅ 중복된 컬럼 삭제
df.drop(columns=[
    "ID"
], inplace=True)

In [89]:
# ✅ 동일한 의미의 중복 컬럼 리스트
duplicate_columns = {

    "키": ['키 (cm)', "키"],
    "허리둘레": ["허리둘레 (cm)","허리둘레"]

}

In [90]:
df.columns

Index(['user_id', '이름', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성',
       '운동 확률', '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', '키 (cm)',
       '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준'],
      dtype='object')

In [8]:
# ✅ 컬럼명 변경 딕셔너리
rename_columns = {
    "허리둘레": "허리둘레 (cm)",
    "키": "키 (cm)",
    "운동 확률": "운동 점수",
    "식사 확률": "식사 점수"
}

In [10]:
# 컬럼명 변경
df = df.rename(columns=rename_columns)

In [11]:
df.columns

Index(['user_id', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성', '운동 점수',
       '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', '키 (cm)',
       '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준', 'gender', 'age',
       'height', 'weight', 'goal_weight', 'waist', 'systolic_bp',
       'diastolic_bp', 'cholesterol', 'activity_level', 'activity_level_code',
       '허리둘레 (cm)', 'HDL콜레스테롤', 'LDL콜레스테롤', '트리글리세라이드', '흡연상태', '음주여부',
       '혈압 차이', '총콜레스테롤', '고혈당 위험', '간 지표', '비만 위험 지수', '식전혈당(공복혈당)'],
      dtype='object')

In [6]:
df

,user_id,성별,연령대,BMI,현재 체중,목표 체중,운동 가능성,운동 확률,식단 개선 필요성,식단 확률,...,LDL콜레스테롤,트리글리세라이드,흡연상태,음주여부,혈압 차이,총콜레스테롤,고혈당 위험,간 지표,비만 위험 지수,식전혈당(공복혈당)
0,게스트,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
300,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
301,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
302,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
303,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0

In [12]:
df.to_csv("predictions.csv", index=False)

In [96]:
# ✅ 중복된 컬럼 삭제
df.drop(columns=[
    "이름"
], inplace=True)

In [120]:
# ✅ 중복된 컬럼 병합 (존재하는 값 중 첫 번째 값 유지)
for new_col, old_cols in duplicate_columns.items():
    existing_cols = [col for col in old_cols if col in df.columns]  # 실제 존재하는 컬럼만 선택
    if len(existing_cols) > 1:
        df[new_col] = df[existing_cols].bfill(axis=1).iloc[:, 0]  # 첫 번째 존재하는 값 선택
        df.drop(columns=existing_cols[1:], inplace=True)  # 첫 번째 컬럼 제외하고 나머지는 삭제

In [13]:
df

,user_id,성별,연령대,BMI,현재 체중,목표 체중,운동 가능성,운동 점수,식단 개선 필요성,식단 확률,...,LDL콜레스테롤,트리글리세라이드,흡연상태,음주여부,혈압 차이,총콜레스테롤,고혈당 위험,간 지표,비만 위험 지수,식전혈당(공복혈당)
0,게스트,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",🔍 예측을 실행하세요,"('🚨 모델이 로드되지 않았습니다!', 0)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,남성,5.0,24.22,70.0,65.0,🔍 예측을 실행하세요,0.00%,🔍 예측을 실행하세요,0.00%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
300,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
301,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
302,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0
303,게스트,남성,25,24.22,NaN,NaN,NaN,45,NaN,45,...,100.0,150.0,비흡연,비음주,40.0,300.0,NaN,40.0,3.3,100.0

In [125]:
# ✅ 후처리 (범위 초과 값 정리)
df["허리둘레 (cm)"] = df["허리둘레 (cm)"].clip(lower=50, upper=150)
df["수축기혈압(최고 혈압)"] = df["수축기혈압(최고 혈압)"].clip(lower=80, upper=200)
df["이완기혈압(최저 혈압)"] = df["이완기혈압(최저 혈압)"].clip(lower=40, upper=130)
df["나이"] = df["나이"].clip(lower=10, upper=100)
df["키 (cm)"] = df["키 (cm)"].clip(lower=100, upper=250)
df["현재 체중"] = df["현재 체중"].clip(lower=30, upper=200)
df["목표 체중"] = df["목표 체중"].clip(lower=30, upper=200)
df["콜레스테롤 지수"] = df["콜레스테롤 지수"].clip(lower=100, upper=300)

In [122]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [123]:
# ✅ 수치형 컬럼 확인 (NaN 값이 있는 컬럼만 선택)
numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()
nan_columns = df[numeric_columns].isna().sum()
nan_columns = nan_columns[nan_columns > 0].index.tolist()  # NaN이 있는 컬럼만 선택

In [127]:
# ✅ 다중대체법(IterativeImputer) 적용 - NaN 값이 있는 컬럼만 변환
imputer = IterativeImputer(max_iter=10, random_state=42)
imputed_values = imputer.fit_transform(df[nan_columns])  # 결과는 Numpy 배열

/opt/anaconda3/envs/hi/lib/python3.10/site-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: [ 0  5  7 15]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(

In [128]:
# ✅ NaN 값이 있는지 확인
if df.isna().sum().sum() == 0:
    print("✅ NaN 값이 모두 채워졌습니다!")
else:
    print("🚨 일부 NaN 값이 남아 있습니다. 다시 확인해주세요!")

🚨 일부 NaN 값이 남아 있습니다. 다시 확인해주세요!

In [131]:
# ✅ 문제 해결: 모든 수치형 컬럼을 float로 변환
numeric_columns = [
    "허리둘레 (cm)", "수축기혈압(최고 혈압)", "이완기혈압(최저 혈압)", "나이",
    "키 (cm)", "현재 체중", "목표 체중", "콜레스테롤 지수"
]
for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")  # 변환 불가한 값은 NaN 처리

In [132]:
# ✅ 다중대체법(IterativeImputer) 적용
imputer = IterativeImputer(max_iter=10, random_state=42)
df[numeric_columns] = imputer.fit_transform(df[numeric_columns])

/opt/anaconda3/envs/hi/lib/python3.10/site-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [134]:
df.columns

Index(['user_id', '성별', '연령대', 'BMI', '현재 체중', '목표 체중', '운동 가능성', '운동 확률',
       '식단 개선 필요성', '식단 확률', '나이', '예측 날짜', '허리둘레 (cm)', '키 (cm)',
       '수축기혈압(최고 혈압)', '이완기혈압(최저 혈압)', '콜레스테롤 지수', '활동 수준'],
      dtype='object')